name: Attach AdministratorAccess Policy

on:
  workflow_call:
    inputs:
      project_name:
        description: 'The GitHub repository name'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      role_to_assume:
        description: 'AWS Role to Assume'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  attach-admin-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Debug AWS credentials configuration
        run: aws sts get-caller-identity

      - name: Attach AdministratorAccess Policy
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
        run: |
          github_action_role="$PROJECT_NAME-GitHubActionsRole"
          admin_policy_arn="arn:aws:iam::aws:policy/AdministratorAccess"
          echo "[INFO] Attaching $admin_policy_arn to $github_action_role"
          set +e
          output=$(aws iam attach-role-policy --role-name "$github_action_role" --policy-arn "$admin_policy_arn" 2>&1)
          rc=$?
          set -e
          if [[ $rc -eq 0 ]]; then
            echo "[INFO] AdministratorAccess attached successfully."
          elif [[ "$output" == *"Duplicate"* || "$output" == *"already attached"* ]]; then
            echo "[INFO] AdministratorAccess policy already attached. Continuing."
          else
            echo "[ERROR] Failed to attach policy: $output"
            exit $rc
          fi
