name: Deploy UI

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
      s3_bucket:
        description: 'S3 Bucket Name'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      role_to_assume:
        description: 'AWS Role to Assume'
        required: true
        type: string
      ecr_repository_name:
        description: 'AWS ECR Repository'
        required: true
        type: string
      aws_region_dev:
        description: 'AWS Region for development'
        type: string
        default: 'us-west-2'
      aws_account_id_dev:
        description: 'AWS Account ID for development'
        type: string
        default: '905418256626'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ inputs.aws_account_id_dev }}  # Cross-account ECR registry

      - name: Pull Docker image and extract artifact
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{inputs.ecr_repository_name}}
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker create --name extract_container $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker cp extract_container:/app/artifact.zip ./artifact.zip
          docker rm extract_container

      - name: Unzip artifact using busybox
        run: |
          mkdir dist
          docker run --rm -v $(pwd):/work alpine:3.14 /bin/sh -c "cd /work && busybox unzip artifact.zip -d dist"

      - name: Sync to S3
        run: |
          aws s3 rm s3://${{ inputs.s3_bucket }}/ --recursive
          aws s3 cp dist/. s3://${{ inputs.s3_bucket }}/ --recursive
