name: Deploy Lambda

on:
  workflow_call:
    inputs:
      project_name:
        description: 'Project Name'
        required: true
        type: string
      aws_account_id:
        description: 'AWS Account Id'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      lambda_bucket_prefix:
        description: 'The bucket prefix for the lambdas'
        required: true
        type: string
      role_to_assume:
        description: 'AWS Role to Assume'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Lambda function
        run: |
          cd app
          zip -r ../${{ inputs.project_name }}.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Upload Lambda zip to S3
        run: |
          aws s3 cp ${{ inputs.project_name }}.zip s3://${{ inputs.lambda_bucket_prefix}}-${{ inputs.aws_account_id}}/${{ inputs.project_name }}/${{ inputs.project_name }}.zip
