name: Deploy Lambda

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      working_dir:
        description: 'The directory of the Lambda function'
        required: false
        default: '.'
        type: string
    outputs:
      checksum:
        description: "The checksum of the artifact"
        value: ${{ jobs.upload.outputs.checksum }}


permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_dir }}
    outputs:
      checksum: ${{ steps.checksum.outputs.checksum }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Lambda function
        run: |
          cd app
          zip -r ../${{ github.event.repository.name }}.zip .
          cd ..

      - name: Calculate checksum
        id: checksum
        run: |
          shasum -a 256 ${{ github.event.repository.name }}.zip > checksum.txt
          CHECKSUM=$(cut -d ' ' -f 1 checksum.txt)
          echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload Lambda zip to S3
        run: |
          aws s3 cp ${{ github.event.repository.name }}.zip s3://${{ vars.LAMBDA_BUCKET_PREFIX}}-${{ vars.AWS_ACCOUNT_ID}}/${{ github.event.repository.name }}/${{ github.event.repository.name }}.zip
