name: Lookup and Validate

on:
  workflow_call:
    inputs:
      aws_account_id:
        type: string
        required: true
      aws_region:
        type: string
        required: true
      role_to_assume:
        type: string
        required: true
      environment:
        type: string
        required: true
      project_name:
        type: string
        required: true
      ref:
        type: string
        required: true
    outputs:
      ecr_tag:
        description: "ECR Tag for the deployment"
        value: ${{ jobs.lookup_and_validate.outputs.ecr_tag }}
      validation_dev_passed:
        description: "Whether development validation passed"
        value: ${{ jobs.lookup_and_validate.outputs.validation_dev_passed }}

jobs:
  lookup_and_validate:
    runs-on: ubuntu-latest
    outputs:
      ecr_tag: ${{ steps.get_ecr_tag.outputs.ecr_tag }}
      validation_dev_passed: ${{ steps.validate_version_dev.outputs.validation_dev_passed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
      
      - name: Extract tag from ref
        id: extract_tag
        run: |
          if [[ "${{ inputs.environment }}" == "development" ]]; then
            SHORT_SHA=$(git rev-parse --short=7 ${{ inputs.ref }})
            
            # Validate format
            if [[ $SHORT_SHA =~ ^[0-9a-f]{7}$ ]]; then
              TAG=$SHORT_SHA
              echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
              echo "Using commit SHA: $TAG"
            else
              echo "Error: Could not extract valid 7-character commit hash"
              exit 1
            fi
          elif [[ "${{ inputs.environment }}" == "production" ]]; then
            REF=${{ inputs.ref }}
            if [[ "$REF" == refs/tags/* ]]; then
              TAG=${REF#refs/tags/}
              echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
            else
              echo "Error: This workflow should be triggered by a tag."
              exit 1
            fi
          else
            echo "Unsupported environment"
            exit 1
          fi

      - name: Get ECR Tag
        id: get_ecr_tag
        run: |
          ECR_TAG=$(aws ecr describe-images --repository-name ${{ inputs.project_name }}-repo \
                    --query 'sort_by(imageDetails,& imagePushedAt)[*].{imageTag:imageTags[0]}' \
                    --output text | grep ${{ steps.extract_tag.outputs.TAG }} | head -n 1)
          echo "ecr_tag=$ECR_TAG" >> "$GITHUB_OUTPUT"

      - name: Validate Version for Development
        id: validate_version_dev
        if: ${{ inputs.environment == 'development' }}
        run: |
          ECR_TAG=${{ steps.get_ecr_tag.outputs.ecr_tag }}
          if ! [[ "$ECR_TAG" =~ ^[0-9a-f]{7}$ ]]; then
            echo "Error: Only 7-character commit SHAs version are allowed for development deployments. Found version: $ECR_TAG"
            echo "validation_dev_passed=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi
          echo "validation_dev_passed=true" >> "$GITHUB_OUTPUT"

      - name: Debug Outputs
        run: |
          echo "ECR Tag: ${{ steps.get_ecr_tag.outputs.ecr_tag }}"
          echo "Validation Dev Passed: ${{ steps.validate_version_dev.outputs.validation_dev_passed }}"