name: Lookup and Validate

on:
  workflow_call:
    inputs:
      aws_account_id:
        type: string
        required: true
      aws_region:
        type: string
        required: true
      role_to_assume:
        type: string
        required: true
      environment:
        type: string
        required: true
      project_name:
        type: string
        required: true
      ref:
        type: string
        required: true

jobs:
  lookup_and_validate:
    runs-on: ubuntu-latest
    outputs:
      ecr_tag: ${{ steps.get_ecr_tag.outputs.ecr_tag }}
      validation_passed: ${{ steps.validate_version.outputs.validation_passed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Extract tag from ref
        id: extract_tag
        run: |
          REF=${{ inputs.ref }}
          if [[ "$REF" == refs/tags/* ]]; then
            TAG=${REF#refs/tags/}
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "Error: This workflow should be triggered by a tag."
            exit 1
          fi

      - name: Get ECR Tag
        id: get_ecr_tag
        run: |
          ECR_TAG=$(aws ecr describe-images --repository-name ${{ inputs.project_name }}-repo \
                    --query 'sort_by(imageDetails,& imagePushedAt)[*].{imageTag:imageTags[0]}' \
                    --output text | grep $TAG | head -n 1)
          echo "ECR_TAG=$ECR_TAG" >> $GITHUB_ENV
          echo "ECR_TAG=$ECR_TAG" >> $GITHUB_OUTPUT

      - name: Validate Version for Production
        id: validate_version
        if: ${{ inputs.environment == 'production' }}
        run: |
          if ! [[ ${{ env.ECR_TAG }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Only semantic versioning is allowed for production deployments. Found version: ${{ env.ECR_TAG }}"
            exit 1
          fi
          echo "validation_passed=true" >> $GITHUB_OUTPUT