name: Post Deployment Tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to test'
        required: true
        type: string
      working_dir:
        description: 'The directory of the Lambda function'
        required: false
        default: '.'
        type: string
      role_to_assume:
        description: 'the aws role to assume'
        required: false
        default: ''
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  post-deployment-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt
          cd ../tests
          pip install -r requirements_test.txt

      - name: Set default artifact name if not provided
        id: set_artifact_name
        run: |
          if [ -z "${{ inputs.role_to_assume }}" ]; then
            echo "role_to_assume=${{ vars.ROLE_TO_ASSUME }}" >> "$GITHUB_ENV"
          else
            echo "role_to_assume=${{ inputs.role_to_assume }}" >> "$GITHUB_ENV"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.role_to_assume }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run tests
        run: |
          cd tests/post-deployment
          pytest
