name: Style Check for Python

on:
  workflow_call:
    inputs:
      working_dir:
        description: 'The directory of the Lambda function'
        required: false
        default: '.'
        type: string

jobs:
  style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .