name: Terraform

on:
  workflow_call:
    inputs:
      project_name:
        description: 'Lambda name'
        required: true
        type: string
      aws_account_id_dev:
        description: 'The AWS account id'
        required: true
        type: string
        default: '905418256626' 
      aws_account_id_prod:
        description: 'The AWS account id'
        required: true
        type: string
        default: '533267144634' 
      aws_region_dev:
        description: 'DEV AWS Region'
        required: true
        type: string
        default: 'us-west-2' 
      aws_region_prod:
        description: 'PROD AWS Region'
        required: true
        type: string
        default: 'us-west-2' 
      org_aws_region:
        description: 'ORG AWS Region'
        required: true
        type: string
      org_aws_account_id:
        description: 'ORG AWS Account ID'
        required: true
        type: string
      role_to_assume:
        description: 'TF Init Dev Role to Assume'
        type: string
        default: 'Python-TF-Init-GitHubActionsRole' 

permissions:
  id-token: write
  contents: read

jobs:
  service-init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4

      - name: Set up GitHub authentication for Cruft
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Clone cookiecutter-lambda template repository
        run: |
          mkdir -p working_directory
          mkdir -p working_directory/lambda-template
          git clone https://github.com/ib-agent/cookiecutter-lambda.git working_directory/lambda-template
          rm -rf working_directory/lambda-template/.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install cookiecutter cruft
          sudo apt-get install -y jq

      - name: Initialize Lambda
        run: |
          PROJECT_NAME=${{ inputs.project_name }}
          cookiecutter --no-input --output-dir working_directory working_directory/lambda-template project_name=$PROJECT_NAME

      - name: List working directory structure
        run: |
          echo "Directory structure of /tmp/working_directory:"
          apt-get update && apt-get install -y tree
          tree -a working_directory

      - name: Ensure services directory exists
        run: mkdir -p services

      - name: Move Lambda to services directory
        run: |
          PROJECT_NAME=${{ inputs.project_name }}
          mv working_directory/$PROJECT_NAME services/$PROJECT_NAME

      - name: Upload services directory as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.project_name }}
          path: services/${{ github.event.inputs.project_name }}

  init:
    needs:
      - service-init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, production]
    steps:
      - name: Set env
        id: set_env
        run: |
          echo "[INFO] Environment: ${{ matrix.environment }}"
          if [ "${{ matrix.environment }}" == "development" ]; then
            echo "aws_account_id=${{ inputs.aws_account_id_dev }}" >> "$GITHUB_OUTPUT"
            echo "aws_region=${{ inputs.aws_region_dev }}" >> "$GITHUB_OUTPUT"
            echo "org_aws_region=${{ inputs.org_aws_region }}" >> "$GITHUB_OUTPUT"
            echo "org_aws_account_id=${{ inputs.org_aws_account_id }}" >> "$GITHUB_OUTPUT"
            role_to_assume="arn:aws:iam::${{ inputs.aws_account_id_dev }}:role/${{ inputs.role_to_assume }}"
            echo "role_to_assume=$role_to_assume" >> "$GITHUB_OUTPUT"
          else
            echo "aws_region=${{ inputs.aws_region_prod }}" >> "$GITHUB_OUTPUT"
            echo "aws_account_id=${{ inputs.aws_account_id_prod }}" >> "$GITHUB_OUTPUT"
            echo "org_aws_region=${{ inputs.org_aws_region }}" >> "$GITHUB_OUTPUT"
            echo "org_aws_account_id=${{ inputs.org_aws_account_id }}" >> "$GITHUB_OUTPUT"
            role_to_assume="arn:aws:iam::${{ inputs.aws_account_id_prod }}:role/${{ inputs.role_to_assume }}"
            echo "role_to_assume=$role_to_assume" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Services if Not Exist
        run: |
          if [ ! -d "services" ]; then
            mkdir services
            echo "services directory created."
          fi

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.project_name }}

      - name: Move Artifact to Services Directory
        run: |
          mv ${{ inputs.project_name }} services/
          echo "$PROJECT_NAME moved to services directory."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.set_env.outputs.role_to_assume }}
          aws-region: ${{ steps.set_env.outputs.aws_region }}

      - name: Debug AWS credentials configuration
        run: |
          aws sts get-caller-identity

      - name: Check S3 State Bucket exist
        env:
          AWS_ACCOUNT_ID: ${{ steps.set_env.outputs.aws_account_id }}
        run: |
          state_bucket_name="cabernet-ai-$AWS_ACCOUNT_ID-state-bucket"
          # Check if the bucket exists
          if aws s3api head-bucket --bucket $state_bucket_name 2>/dev/null; then
            echo "[INFO] State bucket exists on aws account: $AWS_ACCOUNT_ID"
          else
            echo "[ERROR] State bucket does not exist on aws account: $AWS_ACCOUNT_ID"
            exit 1
          fi

      - name: Check & create DynamoDB Table
        env:
          PROJECT_NAME: ${{ inputs.project_name }} 
        run: |
          # Main Lock State DynamoDB Table
          main_table_name="$PROJECT_NAME-main-lock-table" 
          if aws dynamodb describe-table --table-name $main_table_name 2>/dev/null; then
            echo "[INFO] DynamoDB table $main_table_name already exists."
          else
            echo "[INFO] Creating DynamoDB table: $main_table_name"
            aws dynamodb create-table --table-name $main_table_name \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
          fi

      - name: Replace value for default policy files 
        working-directory: ./{{ cookiecutter.project_name }}/tf/default-policy
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          AWS_ACCOUNT_ID: ${{ steps.set_env.outputs.aws_account_id }} 
          AWS_REGION: ${{ steps.set_env.outputs.aws_region }}
          ORG_AWS_REGION: ${{ steps.set_env.outputs.org_aws_region }}
          ORG_AWS_ACCOUNT_ID: ${{ steps.set_env.outputs.org_aws_account_id }}
        run: |
          echo "[INFO] Replacing placeholders in policy files..."
          find . -type f -name "*.json" -exec sed -i \
            -e 's|\${AWS_REGION}|'"$AWS_REGION"'|g' \
            -e 's|\${AWS_ACCOUNT_ID}|'"$AWS_ACCOUNT_ID"'|g' \
            -e 's|\${ORG_AWS_REGION}|'"$ORG_AWS_REGION"'|g' \
            -e 's|\${ORG_AWS_ACCOUNT_ID}|'"$ORG_AWS_ACCOUNT_ID"'|g' \
            -e 's|\${PROJECT_NAME}|'"$PROJECT_NAME"'|g' \
            -e 's|\${USER_NAME}|'"$GITHUB_REPOSITORY_OWNER"'|g' \
            {} +
          
      - name: Create GitHubActionsRole for project
        working-directory: ./services/${{ inputs.project_name }}/tf/default-policy
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
        run: |
          github_action_role="$PROJECT_NAME-GitHubActionsRole"
          policy_file="TrustPolicy.json"
          if aws iam get-role --role-name $github_action_role > /dev/null 2>&1; then
            echo "[INFO] IAM role $github_action_role already exists."
          else
            echo "[INFO] Creating IAM role $github_action_role"
            aws iam create-role \
            --role-name $github_action_role \
            --assume-role-policy-document file://$policy_file 
          fi

      - name: Create policies & attatch to GitHubActionsRole 
        working-directory: ./services/${{ inputs.project_name }}/tf/default-policy
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
        run: |
          github_action_role="$PROJECT_NAME-GitHubActionsRole"

          github_policy_files=("GitHubActionsPolicy.json" "AccessPolicy.json")

          # Loop through each file
          for policy_file in "${github_policy_files[@]}"; do
            echo "[INFO] File: $policy_file"
            if [[ "$policy_file" == "GitHubActionsPolicy.json" ]]; then  
              github_action_policy="$PROJECT_NAME-GitHubActionsPolicy"
            elif [[ "$policy_file" == "AccessPolicy.json" ]]; then  
              github_action_policy="$PROJECT_NAME-AccessPolicy"
            else
              echo "[INFO] invalid file"
            fi
            
            # check if the policy exists
            policy_arn=$(aws iam list-policies --query "Policies[?PolicyName=='$github_action_policy'].Arn" --output text 2>/dev/null)
            if [ -z "$policy_arn" ]; then
              echo "[INFO] Creating: $github_action_policy"
              aws iam create-policy --policy-name $github_action_policy --policy-document file://$policy_file
              policy_arn=$(aws iam list-policies --query "Policies[?PolicyName=='$github_action_policy'].Arn" --output text 2>/dev/null)
            else
              echo "[INFO] $github_action_policy already exists."
            fi

            echo $policy_arn

            # Check if the policy is attached
            policy_is_attached=$(aws iam list-attached-role-policies --role-name $github_action_role \
                --query "AttachedPolicies[?PolicyArn=='$policy_arn']" --output text)

            # Attach the policy if not attached
            if [ -z "$policy_is_attached" ]; then
                echo "[INFO] Attach $github_action_policy to $github_action_role"
                aws iam attach-role-policy --role-name $github_action_role --policy-arn $policy_arn
            else
                echo "[INFO] $github_action_policy is already attached in $github_action_role."
            fi
          done
