name: Terraform

on:
  workflow_call:
    inputs:
      github_repository:
        description: 'The GitHub repository name'
        required: true
        type: string
      aws_account_id:
        description: 'The AWS account id'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
      role_to_assume:
        description: 'AWS Role to Assume'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  check-new-policy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Debug AWS credentials configuration
        run: |
          aws sts get-caller-identity

      - name: Check for modified policy JSON files
        id: check-modified-files
        run: |
          # Get modified policy JSON files in the 'tf' directory and exclude child directory 
          modified_files=$(git diff --name-only HEAD~1 HEAD | grep '^tf/[^/]*\.json$')

          if [ -n "$modified_files" ]; then
            echo "[INFO] Modified files found: $modified_files"
            echo "modified=true" >> "$GITHUB_OUTPUT"
          else
            echo "[INFO] No modified files found."
            echo "modified=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create and attach temporary policy 
        if: steps.check-modified-files.outputs.modified == 'true'
        working-directory: tf/
        env:
          PROJECT_NAME: ${{ inputs.github_repository }}
          AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
          MODIFIED_FILES: ${{ steps.check-modified-files.outputs.modified_files }}
        run: |
          # Get the current date in the format YYYYMMDDHHMMSS with GMT-6 offset
          timestamp=$(date -u +"%Y%m%d%H%M%S" -d '-6 hours')
          echo "timestamp=$timestamp" >> "$GITHUB_OUTPUT"

          # GitHubActionsRole
          github_action_role="$PROJECT_NAME-GitHubActionsRole"

          # Get modified policy JSON files in the 'tf' directory and exclude child directory 
          modified_files=$(git diff --name-only HEAD~1 HEAD | grep '^tf/[^/]*\.json$')

          for file in $modified_files; do
            # Create policy from the JSON file
            file_name=$(echo $file | cut -d'/' -f2)
            policy_name="$(basename $file_name .json)-temporary-$timestamp"
            
            echo "[INFO] Create policy $policy_name"
            aws iam create-policy \
              --policy-name $policy_name \
              --policy-document file://$file_name
            
            # Attach policy to the GitHubActionsRole
            echo "[INFO] Attach $policy_name to $github_action_role" 
            aws iam attach-role-policy \
              --role-name $github_action_role \
              --policy-arn "arn:aws:iam::$AWS_ACCOUNT_ID:policy/$policy_name"
          done

  terraform:
    runs-on: ubuntu-latest
    needs:
      - check-new-policy

    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Debug AWS credentials configuration
        run: |
          aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Set up GitHub authentication for Terraform modules
        run: |
          git config --global url."https://$GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Terraform Init
        run: ./terraform-init.sh ${{ inputs.aws_account_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out=plan.tfplan
        env:
          TF_VAR_aws_account_id: ${{ inputs.aws_account_id }}
          TF_VAR_region: ${{ inputs.aws_region }}
          TF_VAR_github_repository: ${{ inputs.github_repository }}
          TF_VAR_github_username: ${{ secrets.WORKFLOW_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == '2'
        run: terraform apply -auto-approve plan.tfplan
        env:
          TF_VAR_aws_account_id: ${{ inputs.aws_account_id }}
          TF_VAR_region: ${{ inputs.aws_account_id }}
          TF_VAR_github_repository: ${{ inputs.github_repository }}
          TF_VAR_github_username: ${{ secrets.WORKFLOW_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Detach and Delete Temporary Policies
        if: needs.check-new-policy.outputs.modified == 'true'
        env:
          PROJECT_NAME: ${{ inputs.github_repository }}
          timestamp: ${{ needs.check-new-policy.outputs.timestamp }}
        run: |
          github_action_role="$PROJECT_NAME-GitHubActionsRole"
          temporary_policy_arn=$(aws iam list-attached-role-policies --role-name GitHubActionsRole --query "AttachedPolicies[?contains(PolicyName, '-temporary-$TIMESTAMP')].PolicyArn" --output text)
          for policy_arn in $temporary_policy_arn; do
            echo "[INFO] Detach $policy_arn to $github_action_role"
            aws iam detach-role-policy --role-name GitHubActionsRole --policy-arn $policy_arn

            echo "[INFO] Delete $policy_arn"
            aws iam delete-policy --policy-arn $policy_arn
          done
