name: Terraform

on: workflow_call

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify assumed role
        run: |
          aws sts get-caller-identity
          aws iam get-role --role-name GitHubActionsRole

      - name: Debug S3 Acceleration
        run: |
          aws s3api get-bucket-accelerate-configuration --bucket helloworld-ui-bucket

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Verify Terraform and AWS CLI versions
        run: |
          terraform version
          aws --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        env:
          TF_LOG: DEBUG
          AWS_SDK_LOAD_CONFIG: 1
          AWS_DEBUG: 1

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan