name: Test

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: 'Python version to use'
        required: false
        default: '3.12'  # Set the default to Python 3.12

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r tests/requirements_test.txt

      - name: Run tests with coverage
        run: |
          coverage run --rcfile=.coveragerc -m pytest

      - name: Enforce Coverage Threshold
        run: |
          coverage report --rcfile=.coveragerc
