name: Deploy Lambda

on:
  workflow_call:
    inputs:
      working_dir:
        description: 'The directory of the Lambda function'
        required: false
        default: '.'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          cd tests
          pip install -r requirements_test.txt

      - name: Run tests
        run: |
          cd tests/unit
          pytest

      - name: Run tests with coverage
        run: |
          cd tests/unit
          coverage run --rcfile=.coveragerc -m pytest

      - name: Enforce Coverage Threshold
        run: |
          cd tests/unit
          coverage report --rcfile=.coveragerc