name: Trigger Smoke Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  trigger-smoke-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Execute Step Function
        uses: ./.github/workflows/step-function-executor.yaml
        with:
          state_machine_arn: "arn:aws:states:${{ vars.AWS_REGION }}:${{ vars.AWS_ACCOUNT_ID }}:stateMachine:VDRSmokeTestStateMachine"
          execution_name_prefix: "smoketest"
          input_data: |
            {
              "environment": "${{ inputs.environment }}",
              "company_list": ["dunder_mifflin", "ollie_pets_2"]
            }
          include_github_context: "true"